### ISSUE TITLE
Zoom and pan bounces back to first position

### ISSUE THREAD

**Issue by miladrasooli** [michelecocuccio/simple-react-lightbox#135]
**Describe the bug**
When zooming on a large image , the image zooms in and if you want to pan to the areas outside the screen it just bounces back to the center of the image

**Environment*
Create React App

**To Reproduce**
Go to demo website, open an image , zoom in and try to pan anywhere , the image jumps back to its starting position instead of staying at where the user pans to

**Comment by miladrasooli** [comment]
Hi, thanks for quick reply,
I'm using the library with Google Chrome Version 89.0.4389.82 (Official Build) (64-bit) on Windows 10 20H2 64-bit
Here is a video which shows the problem I'm facing:

https://www.dropbox.com/s/j64blrn8jzruxt0/2021-03-12_17-40-30.mp4?dl=0

Thanks

**Comment by michelecocuccio** [comment]
Hello @miladrasooli. At the moment this is how the panzoom work. You need to zoom in more in order to be able to pan the image. As I have mentioned, this is an external library that I am using so it doesn't fully depends on me but I am working to make the lightbox even better, so please check for further updates.

Many thanks
