### ISSUE TITLE
Lazy loading with React Slick

### ISSUE THREAD

**Issue by AbysFlo** [michelecocuccio/simple-react-lightbox#20]
Hello, this is a great tool, but I have only one issue with it, I'm using it with React Slick and I can't seem to be able to use the Lazy Loading option as it would throw me an error :

```
  169 | // Check if the images are loaded using "imagesLoaded" by Desandro (LOVE)
   170 | // When te images are loaded set the state to TRUE and run the function to handle the context
   171 | function handleLoadedImages(array, elementsAreLinks) {
  172 |   imagesLoaded(array, function(instance) {
       | ^  173 |     // Checks if the element (the first one) is an image or a link. If it's a link, the user is using the gallery
   174 |     // And we need to grab the correct source of the image, not the thumbnail
   175 |     const elementType = instance.elements[0].nodeName
```

Which is a shame because if I have a lot of images I won't be able to open the lightbox until all of them have opened?
Would there be a way to provide its own array of images instead of the react-slick one? Or Any other option?

Thank!

**Comment by michelecocuccio** [comment]
@AbysFlo I guess this is a conflict with React Slick and with the logic you are trying to apply.
 
The light-box needs to find the images immediately in order to render theme correctly. If you are lazy loading your images then when the light-box starts I won't find any image. This is not a bug, is intended. The example I showed with React Slick is a basic one but unfortunately I can't cover all the possible case scenarios with every single library. 

Maybe you can use a little bit of JavaScript logic and re-render the component by running a function when new images are loaded after the lazy load? I don't know. Is hard to tell without an example as well. If you want to create a demo on Code Sandbox I might be able to have a closer look.

**Comment by AbysFlo** [comment]
@michelecocuccio Thanks for the input! Wasn't a critic at all, understand completely why it works that way. I don't believe I'm skilled enough to do the re-rendering thingy or create a demo.

I kind of took a dirty approach by taking the SRLWrapper in a hidden side DIV with an "onclick" hook on each <img> to open SLR. Kind of look like that : 
` <div className="col-lg-9 col-xl-9">
      <Slider 
            ref={sliderRef}
            afterChange={
            (currentSlide) => {
             setCurrentSlide( currentSlide + 1 )
             }
            } 
           {...settings}>
           {themedia}                     
     </Slider>
</div>
<div className="d-none">
      <SRLWrapper options={options}>
          {themedia}  
      </SRLWrapper>
</div>`
Definitely not the best option and doesn't come without bug (Display the previous gallery until the new  load of pictures is fully opened.) 

What I'm trying to achieve is, I have pages about cars and a reack-slick gallery displaying the pictures of the cars. The lazy loading part is great because if the car has hundreds of pictures it's so much data to download and maybe won't even be viewed. But I don't have a fullscreen option like lightbox. If there was an option where I don't need the wrapper and just provide the hooks with the pictures for fullscreen display would be amazing.

Now, that's all my nonsense, if you do have an interest in it I can provide you with some access to my development platform to understand what I'm trying to do. Based on the fact that the issue is probably based on my incompetence to produce better code and looking to simplify this part that might or might not interest someone else.

Regardless, thank you for making my life easier with SRL! :)
