### ISSUE TITLE
Control icons not visibile, fixed by adding "buttonsSize"

### ISSUE THREAD

**Issue by jamesroyston** [michelecocuccio/simple-react-lightbox#29]
Hi, I'm running into a bug where the svgs for the lightbox controls are blank. I try to override them with the options prop but that has no effect. 

![image](https://user-images.githubusercontent.com/39611288/79598483-a5571f00-80a9-11ea-8e71-7494e978240b.png)
> _what the autoplay/fullscreen/close buttons look like in my app_

I don't have any global svg or button styles that are cascading into the SRLWrapper (using styled components everywhere). Have you seen this bug before? 

Using `simple-react-lightbox@2.6.8`. 

example of the markup:
```
// app.jsx
    <SimpleReactLightbox>
      <div>
        <ThemeProvider theme={theme}>
          <Router>
            <GlobalStyle />
            <Switch>
              <Route exact path="/">
                <Home />
              </Route>
              <Route path="/details">
                <Details />
              </Route>
            </Switch>
          </Router>
        </ThemeProvider>
      </div>
    </SimpleReactLightbox>
```

```
// component where SRLWrapper is used
    <>
      <SRLWrapper>
        {props.images.map(img => (
          <Img
            role="img"
            key={`image_${img}`}
            src={img}
            alt="pic"
            onClick={() => setFullScreen(!fullScreen)}
          />
        ))}
      </SRLWrapper>
    </>
```

**Comment by michelecocuccio** [comment]
@jamesroyston hello :) This is weird!

Never experienced that bug. I am using Emotion instead of Styled Components (due to the library) size. It could be that the two are colliding somehow? Have you tried to remove your ```<GlobalStyle />``` temporary just to test if it's an issue with it? 

Also have you tried to inspect the buttons and see if something is overriding the style? Try to compare them with the code below (or inspect it with the demo on [https://simple-react-lightbox.dev/](https://simple-react-lightbox.dev/)
<img width="657" alt="Screenshot 2020-04-17 at 19 21 33" src="https://user-images.githubusercontent.com/8071249/79601434-b2433500-80e0-11ea-8cec-be1137dad849.png">

What I will try to do now is to install Styled Component in a CodeSandbox and see if it causes issue with Simple React Lightbox.

Thanks

**Comment by jamesroyston** [comment]
@michelecocuccio Re: the `<GlobalStyles />` component, I have tested with that line removed, to no avail. 

So I did more digging and found out that when inspecting the button element itself, whenever I disabled width, the svg icon appears! 

![image](https://user-images.githubusercontent.com/39611288/79609692-cd03b280-80bc-11ea-9981-c1433f7eb20b.png)

Adding `buttonsSize: '<something in px>` as an option to the `SRLWrapper` fixes it! Maybe there's something wrong with the logic handling default width in the `styles.js` where the `StyledButton`s are declared?

**Comment by jamesroyston** [comment]
I updated the issue title now that I've confirmed the issues is not that overrides aren't working, but that width is an issue for the icons.

**Comment by michelecocuccio** [comment]
@jamesroyston thanks for that.
I will change the title though because that statement is not true. If you check the first example on [https://simple-react-lightbox.dev/](https://simple-react-lightbox.dev/), the first one uses the "default" settings (so no passing any options). The default settings are, of course, defaultProps so the default value of `buttonsSize` is always set to be "40px", it doesn't start as "null" or "0" or "auto" or "undefined". I am glad that you solved the issue this way! It could be helpful for others I guess. Just out curiosity which browser are using so I could some testing? Are you using CRA, Gatsby or NextJS?

Thanks again :)

**Comment by jamesroyston** [comment]
@michelecocuccio found something out! I tried to find out how 'wide' the button needs to be set to in px in order to make it appear. This is my result at a manually set 40px: 
![image](https://user-images.githubusercontent.com/39611288/79612360-2ae6c900-80c2-11ea-847b-db59931b6b27.png)

result at 65px (just now visible): 
![image](https://user-images.githubusercontent.com/39611288/79612533-8022da80-80c2-11ea-8b1f-cd0740611138.png)

I'm on Chrome using CRA.

**Comment by michelecocuccio** [comment]
> @michelecocuccio found something out! I tried to find out how 'wide' the button needs to be set to in px in order to make it appear. When manually set to 40px, I don't have visible icons.
> 
> result at 65px (just now visible):
> ![image](https://user-images.githubusercontent.com/39611288/79612533-8022da80-80c2-11ea-8b1f-cd0740611138.png)
> 
> I'm on Chrome using CRA.

Perfect I will keep this opened for now so if someone will experience the same issue. I will see if I can reproduce this issue because for now nobody reported a similar case and I can't reproduce it. I am doing more testing myself and if I will find a bug I will fix it on the next release :) 

Thank you again @jamesroyston

**Comment by pnorbi1** [comment]
Dear michelecocuccio,

I experienced the same behaviour as above, by default no icons visible, when setting the buttonsSize: "65px" it started to show the icons.
I'm also on Chrome using CRA.

**Comment by jamesroyston** [comment]
@michelecocuccio I believe I found the solution. Tested working in Chrome and Firefox. Question: Is this something you're ok with me making a PR for or do you prefer I just tell you where the bug fix is?

![image](https://user-images.githubusercontent.com/39611288/79626916-c0ea1600-80f9-11ea-857f-3766199e74a5.png)
