### ISSUE TITLE
Not a bug, but a wish !

### ISSUE THREAD

**Issue by fredleput** [michelecocuccio/simple-react-lightbox#34]
Hi,

First of all, thx for this marvellous component, it works like a charm. I'm searching for options i can't find :

- i would like to personalize texts that appear when you mouse over controls (previous, next, close...). Sorry but i'm french and i would like to translate them.
- Also, i didn't find the option to disable full screnn button as we can do with "showDownloadButton"

I would be glad to help with this (if i am able, cause i began developping in react 10 days ago ;))

Thx,
Fred,
Brittany - France

**Comment by michelecocuccio** [comment]
@fredleput 

- I can make the text custom. I don't see a reason for that for know but I will maybe implement this on the next release.
- At the moment the fullscreen button is always visible. If you want to hide it for now you can hide it using CSS by targeting the class '. SRLExpandButton'. I will make it so that you can disable it on the next release.

Thanks a lot

**Comment by fredleput** [comment]
Thx, the reason i thought for customizing text is just for translation
