### ISSUE TITLE
Uncaught TypeError: p.dispatch is not a function

### ISSUE THREAD

**Issue by motrdevua** [michelecocuccio/simple-react-lightbox#40]
Hello Michele!
Sorry for nub question but I'm newbie with react and next.js
I'm tried to made gallery with your plugin but got an error
`Uncaught TypeError: p.dispatch is not a function`
![image](https://user-images.githubusercontent.com/48984371/80911953-5a443980-8d42-11ea-9f71-c28eb9efd301.png)

**Environment*
"react": "16.13.0"
"next": "^9.3.4"

![image](https://user-images.githubusercontent.com/48984371/80912167-c6736d00-8d43-11ea-9bb3-d3900ec11dfd.png)

All pics rendered fine but when page loaded and every click by image leads to

`Uncaught TypeError: p.dispatch is not a function
    at index.es.js:7
    at t (index.es.js:7)
    at index.es.js:7
    at a.<anonymous> (index.es.js:7)
    at a.push../node_modules/simple-react-lightbox/dist/index.es.js.t.emitEvent (index.es.js:1)
    at a.push../node_modules/simple-react-lightbox/dist/index.es.js.a.complete (index.es.js:7)
    at a.push../node_modules/simple-react-lightbox/dist/index.es.js.a.progress (index.es.js:7)
    at index.es.js:7`

I will be grateful for any help!

**Comment by michelecocuccio** [comment]
@motrdevua sorry is a bit hard to tell what's happening but I can see few issues with your code which are not related to the light-box.

- You are not using any state and storing the images in their own state. Therefore after you fetch the images, the component is not re-rendered and I guess my light-box fails.
- You are returning an array with the "galleryPhotos" jsx. I don't know why so maybe that can cause an issue?

Sorry is difficult to understand what the issue is. Maybe try to look how Simple React Lightbox works with API in [my demo](https://simple-react-lightbox.dev/with-api/). Or if you can give access to your repo or put your code in a Code Sandbox environment I could try to have a look.

**Comment by SourceCipher** [comment]
Same issue.. Wrapped images as stated in the docs and as soon as I clicked on the image, I get the same error in the console

**Comment by michelecocuccio** [comment]
@SourceCipher please be careful when reading the documentations :) @motrdevua yes of course you have to wrap your app with the SimpleReactLightbox component.
