### ISSUE TITLE
pseudo element breaks all

### ISSUE THREAD

**Issue by fredleput** [michelecocuccio/simple-react-lightbox#42]
Hi, sorry to come back about this but, since last time i tried to keep my hover effect, but this time with pseudo element.

**Describe the bug**
when hovering the link with data-attribute="SRL", i have a pseudo element who cover the image (transform from scale(0) to scale(1). when i click lightbox doesn't work.

i made some test with ::before, and ::after, same result.

i change my ccs (scale(0.5)) so that overlay doesn't cover entirely the link. click link "directly" works, click "overlay" fails.

Fails : 
![fails](https://user-images.githubusercontent.com/3998154/81458969-af96a580-919d-11ea-909a-cdceb4006a92.png)

Works : 

![works](https://user-images.githubusercontent.com/3998154/81458974-b32a2c80-919d-11ea-8d8d-ef18ccfb0580.png)

Thx,
Fred.

**Comment by fredleput** [comment]
Perhaps comming from here...

`SRLContextComponent.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]).isRequired
}`

i'm not sur about PropTypes.node...

Fred.

**Comment by michelecocuccio** [comment]
@fredleput thanks, nice catch. It has nothing to do with PropTypes :)

I just released a fix in version 2.8.0-2 and tested with a pseudo element on it (I have updated the demo with the Gallery With thumbnails so have a look that confirms it's working on my side).

So that's now fixed in version 2.8.0-2.
