### ISSUE TITLE
Sticky header can interfere with lightbox when z-index is greater than 1

### ISSUE THREAD

**Issue by dmorda** [michelecocuccio/simple-react-lightbox#43]
**Describe the bug**
I have a website that has a sticky header. The sticky header is about 20px and has a z-index of 10. When the lightbox displays, the sticky header is on top of the lightbox controls (e.g., Play, Download, Fullscreen, Close). The only fix I've found is to add the following to my CSS, but it feels a bit like a hack.

```
#SRLLightbox {
  z-index: 20;
}
```
From what I can tell this is the hierarchy that gets added to the DOM.

```
<div id="SRLLightbox"> <=== No z-index
   <div class="SRLStage"> <== z-index of 9991
       [...]
   </div>
</div>
```
So I'm wondering if perhaps the z-index needs bumped up on level to the SRLLightbox or perhaps an option/prop to control the z-index in some way.

**Environment**
* "gatsby": "^2.21.24",
* "gatsby-image": "^2.4.3",
* "simple-react-lightbox": "^2.8.0-5",

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Go to [this website](https://vigilant-ride-023812.netlify.app/)
2. Scroll down to the Unit Plans
3. Click photo

**Screenshots**
<img width="1440" alt="z-index-issue" src="https://user-images.githubusercontent.com/614613/81881048-314f5000-955d-11ea-9c01-b8d34dbd7ff3.png">

**Comment by dmorda** [comment]
P.S. Love this plugin!

**Comment by michelecocuccio** [comment]
@dmorda sure, I am about to release a new version with two major requested features and one big improvement on the thumbnails and I will bump the z-index. What you have done is not an hack anyway, I have provided detailed class names in order to overcome issues like this one. Is difficult to predict many scenarios from a UX/UI perspective but yeah I will definitely bump the z-index a little bit :)
