### ISSUE TITLE
Lightbox image size

### ISSUE THREAD

**Issue by Stallind** [michelecocuccio/simple-react-lightbox#5]
Hi

I wonder if you included some kind of image size option inside the lightbox?

Having a full-size picutre on the site being morphed into something smaller inside the lightbox is a bit weird to me. :) Thanks

**Comment by Stallind** [comment]
I didn't think about the aspect ratio. It makes perfect sense and it "feels" correct. However I feel like it would be nice with a feature to keep the source image size, 
Pink=Lightbox,  
Black= Google drive: 
https://gyazo.com/682618c285613339a0670e5d9482892b

Also there's something I still would like to request some help on. In the gif below my navbar gets a weird efffect upon opening the lightbox. I don't know if it's related to this lightbox or not (im fairly new to react) 
https://gyazo.com/8244320286233d0ee70e82640e3be0ad

**Comment by michelecocuccio** [comment]
Hello @Stallind,
ok that's an interesting feature and I could add a Fullscreen option to the image.

Regarding the second issue is because I am setting the overflow to "hidden" to the body of the page when opening the LightBox to prevent unwanted scroll. For this reason the scrollbar on your page is removed and you see the body moving by 15px. I will amend this issue soon I guess it was a previous attempt to do something else and I left some residual code. 

Many thanks :)

**Comment by michelecocuccio** [comment]
Added with version 2.0. I have added a full-screen button to open the image as full-screen.
