### ISSUE TITLE
Add support for dynamic images

### ISSUE THREAD

**Issue by joshuaiz** [michelecocuccio/simple-react-lightbox#81]
Hello,

My component has dynamically changing images based on what a user clicks however SRL is not updated with the new image(s). It only displays the first image when the component initially renders. 

When the image is updated, it doesn't seem like there's a way to update the SRL wrapper to know this.

```javascript
<SRLWrapper>
    <li>
        <div className="clothing-image">
            <img
                src={currentStyle && currentStyle.image.src} // this src changes based on click of another element
                alt={currentStyle && currentStyle.image.alt}
            />
        </div>
    </li>
</SRLWrapper>
```

It would be great if the `openLightbox()` hook was expanded to not only include the index but the current image source as well. Then this could work with dynamic images as above.

**Comment by michelecocuccio** [comment]
@joshuaiz hello. `<SRLWrapper> `already detects if you add more images and re-render as you can test on the API example on the official website. Changing a link will not cause a re-render because neither props or context were changed. I will try to see if there is a clean way to implement this but this is really an edge case scenario. I will see if I have time to do some work on this for the next release.

**Comment by joshuaiz** [comment]
@michelecocuccio No worries. https://github.com/aautio/react-modal-image can do what I want but SRL is a great plugin and will use it in other projects.

**Comment by michelecocuccio** [comment]
@joshuaiz I have added an observable to the attributes and this will now detect changes to the source image. This has been added in version 3.3.0 and above. Thanks
