### ISSUE TITLE
Uncaught TypeError("Cannot instantiate an arrow function")

### ISSUE THREAD

**Issue by ddsleonardo** [michelecocuccio/simple-react-lightbox#84]
Hi there,

First of all, I'd like to thank you for such a simple and amazing tool!

I've encountered an issue which is closely related to this: https://github.com/codesandbox/codesandbox-client/issues/4300
I tried to implement the SRL in a React App but never got it working, always getting the error mentioned in the title. After a bit of reading, I manage to 'fix' it by adding `"use strict";` to the start of the index.es.js file in my node-modules folder. After doing this, everything worked fine!

Is there a reason why this is not there by default? This is not an issue I had encountered with any other packages before, and I am not really sure what is causing it, especially when apparently most people can use this with no issues.

If it helps, my React app is running on Meteor 1.10.2. Please let me know if more information is required.

Best regards.

**Comment by michelecocuccio** [comment]
Hi @ddsleonardo thanks for your kind comment :) 

The issue that I had with CodeSandbox wasn't related to the Simple React Lightbox but, instead, with CodeSandbox code. I never used Simple React Lightbox with Meteor but it seems to me that this is an issue with the configuration of your project OR with your Typescript config. 

I never added "use strict" by default to Simple React Lightbox as I don't need to run JavaScript in strict mode, as I wanted to avoid that silent errors were thrown as errors. Also this is the first time someone is having this issue so again I am pretty sure this has something to do with your config but I will try and see what's happening especially using Meteor, and if I encounter the same issue I will add Strict mode to the light-box.

**Comment by ddsleonardo** [comment]
Thanks for the prompt reply. Would very much appreciate if you could investigate the interaction with Meteor. Let me know if at any point you'd like more details on package versions or anything.
Other than that I have encountered no issues, so will keep using with the 'fix' for now.

**Comment by michelecocuccio** [comment]
@ddsleonardo I can confirm that the problem is with Meteor as I just run some tests and I was getting the same error. The problem is that for some reasons, Meteor is not supporting the "index.es.js" file which is bundled in an ECMAScript Module aware way. So a solution is to change your import to be:

`import SimpleReactLightbox from "simple-react-lightbox/dist/index"`
and
`import { SRLWrapper } from "simple-react-lightbox/dist/index"`

and this should work without you needing to change the file in the "node_modules" folder which is annoying as it will be recreated every time you run `npm install`.

Let me know if this works for you!
Thanks

**Comment by ddsleonardo** [comment]
Hi @michelecocuccio ,

I have un/reinstalled the package, to make sure I'd get the error again, and I did.
I then changed my imports to the ones above, and I can confirm that this solved the problem!

Many thanks for the prompt support! Amazing work.
Leo.
